dist: trusty

language: cpp

notifications:
  email: false

sudo: false

matrix:
  include:
    - os: linux
    - compiler: gcc

addons:
  apt:
    packages:
    - qt5-default
    - cmake
    - gcc

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake . ${TRAVIS_BUILD_DIR}

script:
  - make
