dist: trusty

language: cpp

notifications:
  email: false

sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qttools5-dev-tools
            - qttools5-dev
            - qt5-default
            - cmake
            - g++-7
      env:
       - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake . ${TRAVIS_BUILD_DIR}

script:
  - make
