dist: trusty

language: cpp

notifications:
  email: false

sudo: required

matrix:
  include:
    - os: linux
    - compiler: gcc

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - qt5-default

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake . ${TRAVIS_BUILD_DIR}

script:
  - make
