dist: trusty

language: cpp

notifications:
  email: false

sudo: false

matrix:
  include:
    - os: linux
      compiler:
      - clang
      - gcc

    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - qt5-default
          - cmake
          - g++-7
    env:
       - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake . ${TRAVIS_BUILD_DIR}

script:
  - make
