language: cpp

# 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置false吧
notifications:
  email: false

# 开启基于容器的Travis CI任务，让编译效率更高。
sudo: false

compiler:
  - clang
  - gcc

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq sqlite3 qt5-dev-tools

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
